version: '3.3'

services:

  mongo:
    image: mongo:latest
    container_name: "productsdb"
    ports: 
      - 27017:27017
    expose: 
      - "27017"
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_INITDB_DATABASE=products

volumes:
  mongo_data: